
import React, { useState } from 'react';
import { v4 as uuidv4 } from 'uuid';
import StoryNarrator from './StoryNarrator';
import { useAuth } from '../../contexts/AuthContext';

export default function RegionStorybook({ region = 'Jungle Trails' }) {
  const [story, setStory] = useState('');
  const [loading, setLoading] = useState(false);
  const [storyId, setStoryId] = useState(null);
  const { user } = useAuth();

  const generateStory = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/turian', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          message: `Create a magical children's story set in ${region} of The Naturverse. Make it educational, fun, and about 3-4 sentences long. Include nature facts and adventure!`,
          userId: user?.id,
          language: 'en'
        })
      });
      const data = await res.json();
      const newStory = data.message || 'Once upon a time in the magical naturverse...';
      setStory(newStory);
      setStoryId(uuidv4());
    } catch (error) {
      console.error('Story generation failed:', error);
      setStory('Something went wrong with the story magic! Try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className='p-6 bg-white rounded-lg shadow-lg max-w-2xl mx-auto'>
      <div className='text-center mb-6'>
        <h2 className='text-3xl font-bold text-nature-green mb-2'>
          📖 {region} Storybook
        </h2>
        <p className='text-gray-600'>Generate magical stories from this enchanted region</p>
      </div>

      <div className='space-y-4'>
        <button
          onClick={generateStory}
          disabled={loading}
          className='w-full bg-nature-green text-white px-6 py-3 rounded-lg hover:bg-green-600 disabled:opacity-50 disabled:cursor-not-allowed font-semibold'
        >
          {loading ? '✨ Creating Magic...' : '🎲 Generate New Story'}
        </button>

        {story && (
          <div className='mt-6 p-6 bg-green-50 rounded-lg border border-green-200'>
            <div className='flex items-center justify-between mb-4'>
              <h3 className='font-bold text-green-800 text-lg'>Your Magical Story:</h3>
              <StoryNarrator text={story} />
            </div>
            <div className='text-gray-800 leading-relaxed text-lg font-medium whitespace-pre-line'>
              {story}
            </div>
            {storyId && (
              <div className='mt-4 text-sm text-gray-500'>
                Story ID: {storyId}
              </div>
            )}
          </div>
        )}
      </div>

      <div className='mt-6 text-center text-sm text-gray-500'>
        <p>Each story is uniquely generated by Turian's AI magic! 🐢✨</p>
      </div>
    </div>
  );
}
